---
title: "Call_Analysis"
author: "may"
date: "7/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(ggthemes)
library(RColorBrewer)
library(plotly)

library(ordinal) 
library(emmeans)
library(multcompView)
```

```{r}
gleaner_universe_r_7_19_19 <- read_excel("~/Dropbox/GLEANER UNIVERSE STUDY/data sheets/gleaner_universe_r_7.19.19.xlsx")
g_u <- gleaner_universe_r_7_19_19

library(readxl)
Call_analysis_avgs_R <- read_excel("~/Dropbox/GLEANER UNIVERSE STUDY/data sheets/Call_analysis_avgs_R.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "text"))
View(Call_analysis_avgs_R)

CA<- Call_analysis_avgs_R


```


PLOTTING THINGS
```{r}
TM <- theme_calc(base_size = 25) + theme(axis.text.x = element_text(angle = 45, hjust=1), plot.background =element_blank()) #tilted x-axis labels and title
```

DATA ORGANIZING THINGS
```{r}
colnames(CA)
## remove NAs
CA <- subset(CA, CA$peak_freq != "NA") 

#order playback
CA$Playback<- factor(CA$Playback, levels = c( "Acla sp." ,     "Aclodes sp."   ,  "Anaxipha sp.", "A. spatulata" , "T. subfalcata", "V. zederstedi"  ,  "C. wheeleri" ,  "D. gigliotosi"  , "Q. gigas" ,  "Z. smaragdina"   ,   "D. diastema" , "H. fleishmanni", "D. ebraccatus" ,  "S. sila"   ,   "P. pustulosus" ,  "H. frenatus" , "T. rapicauda"  , 
    "Beetle flight",  "Frog hopping"  , "Mouse rustles", "White noise"), ordered = TRUE )

```

PLOTTING 
```{r}


p_gu_pf <- ggplot(data = CA, aes(x = Playback, y = peak_freq, colour = Call_type))
#p_gu_pf <- p_gu_pf+ xlim(0,)

p_gu_pf <- p_gu_pf+ geom_point(size = 5)
p_gu_pf <- p_gu_pf+  xlab("Acoustic stimuli")
p_gu_pf <- p_gu_pf+  ylab("Peak Frequency") 
p_gu_pf <- p_gu_pf+ theme(legend.title = element_blank())
p_gu_pf <- p_gu_pf+ TM
p_gu_pf 
ggsave("peak_freq_acoustic_stim.jpg", width = 15)



```

